#!/usr/bin/env bash
# Displays information about the file `best school`.

if [ -e "best school" ]
then
  echo "best school file exists"
  if [ -s "best school" ]
  then
    echo "best school file is not empty"
  else
    echo "best school file is empty"
  fi

  if [ -f "best school" ]
  then
    echo "best school is a regular file"
  fi
else
  echo "best school file does not exist"
fi
